# data processing ...

SYMBOL = 'amzn_'

NUMBER_OF_TABLES_TO_RESERVE_FOR_INFERENCE = 15
NUMBER_OF_SAMPLES_IN_A_FULL_BATCH = 64
NUMBER_OF_SAMPLES_IN_A_SUB_BATCH = 1


PERFORM_INFERENCE = True
PERFORM_BACKTEST = False


PAST_LENGTH = 5000
FUTURE_LENGTH = 1000


IB_PRICE_INDEX = 0
IB_SIZE_INDEX = 1
IB_TIME_INDEX = 3


K_VALUE = 5


PRICE_MLTIPLIER = 1000
PRICE_CLIP_MIN = 0.01
PRICE_CLIP_MAX = 1.3


SIZE_MLTIPLIER = 0.001
SIZE_CLIP_MIN = 0.0001
SIZE_CLIP_MAX = 1.3


TIME_DIFF_MLTIPLIER = 0.00000000027
TIME_CLIP_MIN = 0.0001
TIME_CLIP_MAX = 1.3


LABEL_PRICE_SMA_FOR_Y_CALCULATION = 70
LABEL_2D_MA_INTERVAL = 30
LABEL_COMPANDING_VAL = None
LABEL_MULTIPLIER = 450


# training ...
INFERENCE_AFTER_Nth_BATCH = 10
INFERENCE_EVERY_Nth_BATCH = 10


# inference ...
BACKTEST_PRICE_SMA_PERIOD = 7


BACKTEST_SIGNAL_THRESHOLD_ROUND_DIGIT = 7
BACKTEST_SIGNAL_THRESHOLD_MIN = 0.02
BACKTEST_SIGNAL_THRESHOLD_MAX = 0.6
BACKTEST_SIGNAL_THRESHOLD_MULTIPLIER = 1.26
BACKTEST_BUY_SIGNAL_THRESHOLDS = (1,)
BACKTEST_SELL_SIGNAL_THRESHOLDS = (1,)


BACKTEST_TARGET_VALUES_USD = (1,)
BACKTEST_STOP_LOSS_VALUES_USD = (1,)


SIGNAL_BUY_INDEX = 0
SIGNAL_SELL_INDEX = 1


SAVE_INFERENCE_FILES = False
MIN_PL_TO_SAVE_INFERENCE_FILES = 30

# production ...
PROD_MODEL_PATH_NAME = 'res/***.h5'
PROD_BATCH = 10

PROD_UNDERBID_USD = 0.0

# PROD_TARGET_USD = 0
# PROD_STOP_USD = 0

PROD_TARGET_PERCENT = 0.35
PROD_STOP_PERCENT = 0.25

PROD_BUY_THRESHOLD = 0.375
PROD_SELL_THRESHOLD = -0.375

PROD_NUM_SHARES = 1
